### ISSUE TITLE
Incorrect order of LoC when a ruler is closed

### ISSUE THREAD

**Issue by flesler** [mikaa123/linear#1]
Hi, was taking a look and noticed a problem with [these](https://github.com/mikaa123/linear/blob/master/main.js#L40-L41) lines.

``` js
ruler = undefined;
rulers.splice(rulers.indexOf(ruler), 1);
```

Should be:

``` js
rulers.splice(rulers.indexOf(ruler), 1);
ruler = undefined;
```

Regards

**Comment by mikaa123** [comment]
Thanks man, I appreciate it :)
