### ISSUE TITLE
[Feature suggestion] - A vertically-centered ruler

### ISSUE THREAD

**Issue by zulhfreelancer** [mikaa123/linear#10]
Hi,

I would like to suggest a feature - vertically-centered ruler. When we click for that ruler from the menu bar OR from keyboard shortcut, we get a straight line at the middle of our browser window.

This is just a straight line. Not like the current ruler where it's square in shape.

Love this app! ❤️

**Comment by mikaa123** [comment]
Hi!

Thanks for using the app :)
I'm afraid I'm not sure I understand exactly, could you maybe provide a little screenshot with a rough explanation? That'd be really awesome!

**Comment by zulhfreelancer** [comment]
I'm sorry for bad explanation.

This is what I mean. I vertically-centered straight line. 😊

![0](https://cloud.githubusercontent.com/assets/3416976/12913343/15aae932-cf59-11e5-8697-4a53a81d58fe.jpg)

**Comment by mikaa123** [comment]
I see!
For now I don't want to add features that aren't directly for rulers. I'll keep this around and see if other people are interested though :)

**Comment by radiovisual** [comment]
This could actually be a really cool feature if it was applied directly to rulers, and not just to the screen.  

For example, if you made it easier for users to find the exact center of the rulers:

(Red color used for demonstration only)
![center-of-rulers](https://cloud.githubusercontent.com/assets/5614571/14060253/81860f30-f356-11e5-8226-84ddd531d2d0.png)

**Comment by radiovisual** [comment]
Another thing that could be cool, is if there was a way to launch the rulers to be full-width and full-height of the screen, because then the rulers could mimic the ruler functionality in Photoshop and then @zulhfreelancer's idea suddenly becomes more about rulers and less about the page (assuming you have a way to let users find the exact center of the ruler)...

**Comment by mikaa123** [comment]
mmmm I like the idea of having guides on the ruler a lot!
Something subtle maybe, like dashed lines? That could be a starting point to then move to the full-screen rulers.

**Comment by radiovisual** [comment]
Agreed. Subtle, dashed lines would be great, and then build the "full-screen" feature into a your future feature roadmap. 

I am happy to help if you want to delegate some tasks.

**Comment by mikaa123** [comment]
This project is yours as much as mine: I'd love to have your help! Maybe we should start thinking about a V2 and the features we want to see there.

**Comment by radiovisual** [comment]
Ok, awesome. Let's plan a feature roadmap for V2, make a new branch and get to work! :smile:

**Comment by radiovisual** [comment]
I added a center-guide feature in PR #17 . 

@zulhfreelancer , if and when this PR gets approved/merged, you would be able to use it to get your vertical line on the screen, simply by pulling out a full-screen ruler. Like this:

![fullscreen-center-guide](https://cloud.githubusercontent.com/assets/5614571/14067998/9d077772-f46d-11e5-94be-d633c12c1a0c.png)

In the screenshot above, I made a ruler, then pulled it out to fit the full width of the screen, and toggled on the center-guides using the shortcut <kbd>⌘;</kbd>

**Comment by zulhfreelancer** [comment]
So cool!

**Comment by mikaa123** [comment]
Thanks to #17, this is now kind of possible. It requires to use the ruler fullscreen though.

**Comment by zulhfreelancer** [comment]
So this one is inside v1.2.0?

**Comment by radiovisual** [comment]
@zulhfreelancer , no @mikaa123 has not made a new release or build with the center guide feature in it yet. This feature should arrive in the upcoming release/build `v1.3.0`

**Comment by mikaa123** [comment]
Here we go https://github.com/mikaa123/linear/releases/tag/1.3.0 :)

**Comment by radiovisual** [comment]
Awesome! :+1: :cake:  Since linear's new center guide feature is as close as linear will ever get to this particular feature request (putting a line down the center of the screen), this issue can be closed, right?

**Comment by zulhfreelancer** [comment]
Thank you!
