### ISSUE TITLE
better contrast for ruler lines and text

### ISSUE THREAD

**Issue by radiovisual** [mikaa123/linear#15]
When viewing this ruler across multiple screens on multiple machines, I find that occasionally the rulers are hard to see/read.

Here is a screenshot I took from one of my computer screens (ruler width and height down in the bottom left corner are very difficult to see):

![linear-contrast](https://cloud.githubusercontent.com/assets/5614571/14060317/c449118a-f358-11e5-87fc-3b83cc33ba8c.png)

When I switch to "dark mode", I still have readability issues when there are situations that cause "dark on dark", for example, notice how the width value is now completely unreadable in the bottom left corner of the ruler):

![readability-on-dark](https://cloud.githubusercontent.com/assets/5614571/14061342/09a417c6-f376-11e5-8dfc-3f4207faedeb.png)

I propose that the ruler data (and the ruler lines) get drawn with contrasting lines (double lines with a dark and light lines) so that the styles readably-universal to dark or light situations, or the ruler lines and text data get a subtle but effective background color (or drop shadow?) to help offset the ruler text from the browser or screen text. Something like the image below would make a big difference in universal readability (using the same screenshot example as above, notice how much easier it is to read the width value in the bottom left corner):

![better-contrast](https://cloud.githubusercontent.com/assets/5614571/14061419/a417608c-f377-11e5-875b-08268eaa0703.png)

**Comment by mikaa123** [comment]
:+1: do you think this approach could remove the dark/light themes in favor of a universal one?

**Comment by radiovisual** [comment]
I think the default should be a universal theme, and as long as the universal theme is truly universal enough to be visible/readable under all dark/light scenarios, then there is no need for any other theme...that being said, because there are an infinite number of possible use-cases, being "functionally-universal" is very difficult, so I find, that when it comes to UI, giving the user some flexibility (i.e, customization) is always smart, because then you can let the user decide what works best in their scenario.  So there could be a case for making the universal theme the default, but still allow the user to switch or customize the themes.

**Comment by radiovisual** [comment]
I know this is getting sort of ambitious, but because this tool has web developers in mind, maybe you can expose an option in the settings that lets the user write their own css to style the different elements of the rulers. this would give all the power to the developer to define the way they want the ruler to look, and could be super cool.

**Comment by mikaa123** [comment]
Agreed with the default universal theme. And yes, we could imagine a custom css file. It'd actually be really cool.

**Comment by radiovisual** [comment]
> And yes, we could imagine a custom css file. It'd actually be really cool.

It would be cool! :smile: 

We can talk about how we want to integrate the custom colors. Perhaps we have 3 presets: `default (universal), light and dark` and then two final choices of `custom light` and `custom dark` where they can enter in their own css.  

We could modify the "theme" button to offer a small "tooltip" style popup, letting them select the theme they want for the individual ruler.

What do you think?

**Comment by mikaa123** [comment]
Sounds good, I like the idea of the tooltip over the theme button. By the way, I'm not too fond of that theme button...

For the styles, we could load them directly from `.linear/themes`. For every `.css` file there, an entry is added to the tooltip. By default there could be the 3 files you talked about. They can then add the `custom light/dark.css` to the folder for overrides.

What do you think? Do you have another perspective/idea?

**Comment by mikaa123** [comment]
I created an issue for Custom themes CSS (#19)

**Comment by radiovisual** [comment]
Ok, I will move discussion about the CSS files to the new issue.

Do you think we should close this issue and favor these ideas in the new issue #19 ? Because if we adopt the idea of Custom CSS with Default Themes, then it will solve this problem of needed contrast in the lines and text.

**Comment by mikaa123** [comment]
Let's leave it open so we can talk about the "default" theme (better contrast), and use #19 to talk about custom ones, even though the two area are kinda intertwined...
