### ISSUE TITLE
`brew cask install linear` fails 

### ISSUE THREAD

**Issue by lorefnon** [mikaa123/linear#23]
Unable to install linear using homebrew. 

```
$ brew cask install linear

Error: Cask 'linear' definition is invalid: Bad header line: parse failed
```

**Comment by miklb** [comment]
I get a different error `Permission denied - /Library/Ruby/Gems/2.0.0/specifications/bourbon-4.2.4.gemspec`

**Comment by sscotth** [comment]
Works for me. 
```
➜  ~ brew cask search linear
==> Exact match
linear
➜  ~ brew cask install linear
==> Downloading https://github.com/mikaa123/linear/releases/download/1.3.0/linear.zip
######################################################################## 100.0%
==> Verifying checksum for Cask linear
==> Symlinking App 'linear.app' to '/Users/scott/Applications/linear.app'
🍺  linear staged at '/opt/homebrew-cask/Caskroom/linear/1.3.0' (10266 files, 151M)
```

**Comment by lorefnon** [comment]
The problem was with an outdated homebrew-cask installation on my system. 

On running `brew doctor` I noticed following issue: 

```
Found command `brew-cask` in following places:
    /usr/local/bin/brew-cask
    /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb
```

On investigating further I came across the following notification in the Repo of Homebrew-cask: 

```
Important December 2015 update: Homebrew-Cask will now be kept up to date together with Homebrew (see #15381 for details). If you haven’t yet, run brew uninstall --force brew-cask; brew update to switch to the new system
```

Since I was certain that my homebrew-cask installation predated december 2015, I followed the recommendation and forced uninstallation of the brew-cask that was overriding the bundled version. 

After that the installation worked fine.

**Comment by mikaa123** [comment]
Glad it's working now :)

**Comment by miklb** [comment]
I'm getting the same error about `Permission denied - /Library/Ruby/Gems/2.0.0/specifications/bourbon-4.2.4.gemspec` any thoughts? Homebrew & cask all up to date, no errors or issues after running `brew doctor`.
