### ISSUE TITLE
"Apply theme to all open rulers" requires mouseover(s) for repaint 

### ISSUE THREAD

**Issue by radiovisual** [mikaa123/linear#27]
The new "Apply theme to all open rulers" button in the settings menu DOES work, but for some reason the visual changes to the ruler are only updated (repainted) after you mouseover or focus the ruler window. Occasionally the change happens without mouseover or repaint, but this is rare.

Is anyone else having this problem, or is it just me?

**Comment by mikaa123** [comment]
Yeah, I also have this problem!
