### ISSUE TITLE
settings font-size not working.

### ISSUE THREAD

**Issue by radiovisual** [mikaa123/linear#29]
In the readme.md, it says:

> Uses px or em values; set the default font-size to your convenience.

It's the _"set the default font-size to your convenience"_ part that I am wondering about...

The settings menu has an option for setting the Font Size, **but**:
1. The font-size option in the settings doesn't appear to do anything; and
2. The font-sized entered into the settings window isn't saved into the `settings.json` file, and
3. The font-size entered into the settings window is not reloaded or remembered after the settings window is closed and reopened. 

So should this feature be removed, and we can let the the users override the font size in their own custom theme(s)?

**Comment by mikaa123** [comment]
I think the `font-size` setting is kind of a misnomer. It's not the actual size of the font in the application, but it's the base value used to calculate the `em`. For this reason, I don't think it would be possible to override the `font-size` in the theme.

Thanks for reporting this though, I'll check to see why it's not working correctly.

**Comment by radiovisual** [comment]
Oh, I see. I misunderstood the true purpose of the font-size setting. No problem.
