### ISSUE TITLE
Disable overflow scrolling on Mac OS X

### ISSUE THREAD

**Issue by sbruchmann** [mikaa123/linear#3]
Hello @mikaa123,

it would be nice if the overflow scrolling of a ruler is disabled.

(Pull request incoming ;))

Best regards,
Steffen

**Comment by mikaa123** [comment]
Yes, you're completely right. Looking forward to the PR :)

**Comment by sbruchmann** [comment]
Apparently, `npm`'s network is a bit flaky. It hangs while running `npm install`.

**Comment by mikaa123** [comment]
Yeah that tends to happen sometimes. Have you tried npm cache clean?

**Comment by sbruchmann** [comment]
> Have you tried npm cache clean?

That didn’t do the trick.

Mind if I send a pull request via GitHub’s UI?

**Comment by mikaa123** [comment]
Go ahead, no problem :)

**Comment by sbruchmann** [comment]
@mikaa123 Done. ;) (Untested, though.)
