### ISSUE TITLE
Version 1.4.0 immediately crashes

### ISSUE THREAD

**Issue by vitorgalvao** [mikaa123/linear#31]
Reported on https://github.com/caskroom/homebrew-cask/pull/21909. I can reproduce as well. As soon as I open Linear, it immediately closes. Console output:

```
13/06/16 12:36:21,639   launchservicesd[78] SecTaskLoadEntitlements failed error=22
13/06/16 12:36:21,642   launchservicesd[78] SecTaskLoadEntitlements failed error=22
13/06/16 12:36:21,646   launchservicesd[78] SecTaskLoadEntitlements failed error=22
13/06/16 12:36:21,698   appleeventsd[51]    SecTaskLoadEntitlements failed error=22
13/06/16 12:36:21,731   linear Helper[63516]    GVA info: preferred scaler idx 0
13/06/16 12:36:21,767   com.apple.xpc.launchd[1]    (com.electron.linear.270752[63515]) Service exited with abnormal code: 1
```

OS X 10.11.5 (15F34)

**Comment by mikaa123** [comment]
thanks for the quick report, I'll look into that

**Comment by mikaa123** [comment]
🎱 Should work fine now: https://github.com/mikaa123/linear/releases/tag/1.4.1

**Comment by vitorgalvao** [comment]
Still crashing on 1.4.1.

**Comment by radiovisual** [comment]
1.4.1 works for me, no crashing but I am installing via git/npm install. I think the problem is coming from users who are installing via homebrew.

@vitorgalvao , can you confirm that you installed the new version via homebrew?

**Comment by vitorgalvao** [comment]
> I think the problem is coming from users who are installing via homebrew.

It’s not. Not only does homebrew-cask not alter the software in any way, I’ve tried it manually.

**Comment by radiovisual** [comment]
hm. does it also crash if clone and run via npm?

```
$ git clone https://github.com/mikaa123/linear.git
$ cd linear && npm install && npm start
```

If it crashes, please attach any errors you see in the console.

**Comment by vitorgalvao** [comment]
> does it also crash if clone and run via npm?

Nice call. That way it does not crash. After launching it like that once, launching the downloaded one started to work.

**Comment by radiovisual** [comment]
Ok, good to know. Thanks. 👍
