### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by voronianski** [mikaa123/linear#5]
That's all that I have in installe app 

![](https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-12-18%20%D0%B2%2018.14.00.png)

How it should work?

OS X 10.11.1

**Comment by voronianski** [comment]
Sorry, didn't notice it in top tray, maybe it's worth adding menu items here as well. :)

**Comment by mikaa123** [comment]
No worries, it is a little shy app ;)
Yes, maybe that menu could be used for something...

Thanks for trying it out!
