### ISSUE TITLE
Place linear.json file somewhere besides the home directory

### ISSUE THREAD

**Issue by goronfreeman** [mikaa123/linear#7]
I like to keep my home directory nice and clean, but Linear dumps a json file that is kind of annoying to have there for me. Would it be possible to put it into a hidden folder, or anywhere else besides the home directory? Even just making it a dotfile would work for me.
![screen shot 2016-01-04 at 9 45 43 pm](https://cloud.githubusercontent.com/assets/5210483/12107148/a4df448e-b32c-11e5-826f-8d2223a94d9f.png)

**Comment by mikaa123** [comment]
For sure, it should have been a dotfile from the begining.
Thanks for pointing it out ;)
