### ISSUE TITLE
Serif font in settings

### ISSUE THREAD

**Issue by mischah** [mikaa123/linear#9]
Hi, 

first of all thanks for this awesome electron app. It works like a charm is is damn useful.

I spotted a little visual glitch with the fonts in the settings dialog:

> ![Screenshot](http://cl.ly/1u3k083a3902/linear-screenshot.png)

Reason :arrow_forward: [settings.css](https://github.com/mikaa123/linear/blob/master/src/app/settings/settings.css):

``` css
body {
    font-family: "Open Sans";
    padding-left: 1em;
}
```

So I would say it needs a proper font stack or you have to include the webfonts. Cant you reference the ones within [/src/assets/fonts/](https://github.com/mikaa123/linear/tree/master/src/assets/fonts)?

I could try to create a PR tonight …

**Comment by mikaa123** [comment]
Thanks :)

Yes, you're right. The `settings.html` file is missing this line:
`<link href="../../assets/styles/common.css" rel="stylesheet" type="text/css"/>`

Feel free to do it, otherwise I'll commit late on.

**Comment by mischah** [comment]
:ok_hand:
